
# Spring Development =======================================================================================================

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/product-propose
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

  thymeleaf:
    cache: false
